//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLord.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color Screen_Color_Background {
            get {
                return ((global::System.Drawing.Color)(this["Screen_Color_Background"]));
            }
            set {
                this["Screen_Color_Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RoyalBlue")]
        public global::System.Drawing.Color Screen_Color_Normal {
            get {
                return ((global::System.Drawing.Color)(this["Screen_Color_Normal"]));
            }
            set {
                this["Screen_Color_Normal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 192, 0")]
        public global::System.Drawing.Color Screen_Color_Invisible {
            get {
                return ((global::System.Drawing.Color)(this["Screen_Color_Invisible"]));
            }
            set {
                this["Screen_Color_Invisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Screen_Color_Locked {
            get {
                return ((global::System.Drawing.Color)(this["Screen_Color_Locked"]));
            }
            set {
                this["Screen_Color_Locked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 0")]
        public global::System.Drawing.Color Screen_Color_LockedAndInvisible {
            get {
                return ((global::System.Drawing.Color)(this["Screen_Color_LockedAndInvisible"]));
            }
            set {
                this["Screen_Color_LockedAndInvisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color Screen_Color_Highlight {
            get {
                return ((global::System.Drawing.Color)(this["Screen_Color_Highlight"]));
            }
            set {
                this["Screen_Color_Highlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Screen_MarginLeft {
            get {
                return ((int)(this["Screen_MarginLeft"]));
            }
            set {
                this["Screen_MarginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Screen_MarginTop {
            get {
                return ((int)(this["Screen_MarginTop"]));
            }
            set {
                this["Screen_MarginTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Screen_Color_Headings {
            get {
                return ((global::System.Drawing.Color)(this["Screen_Color_Headings"]));
            }
            set {
                this["Screen_Color_Headings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Screen_CellWidth {
            get {
                return ((int)(this["Screen_CellWidth"]));
            }
            set {
                this["Screen_CellWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Screen_CellHeight {
            get {
                return ((int)(this["Screen_CellHeight"]));
            }
            set {
                this["Screen_CellHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int Print_Title_FontSize {
            get {
                return ((int)(this["Print_Title_FontSize"]));
            }
            set {
                this["Print_Title_FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_Year_Height {
            get {
                return ((int)(this["Print_Year_Height"]));
            }
            set {
                this["Print_Year_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_Year_Width {
            get {
                return ((int)(this["Print_Year_Width"]));
            }
            set {
                this["Print_Year_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Print_Year_MarginLeft {
            get {
                return ((int)(this["Print_Year_MarginLeft"]));
            }
            set {
                this["Print_Year_MarginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_Staff_Height {
            get {
                return ((int)(this["Print_Staff_Height"]));
            }
            set {
                this["Print_Staff_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_Staff_Width {
            get {
                return ((int)(this["Print_Staff_Width"]));
            }
            set {
                this["Print_Staff_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Print_Staff_MarginLeft {
            get {
                return ((int)(this["Print_Staff_MarginLeft"]));
            }
            set {
                this["Print_Staff_MarginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_Rooms_Height {
            get {
                return ((int)(this["Print_Rooms_Height"]));
            }
            set {
                this["Print_Rooms_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_Rooms_Width {
            get {
                return ((int)(this["Print_Rooms_Width"]));
            }
            set {
                this["Print_Rooms_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Print_Rooms_MarginLeft {
            get {
                return ((int)(this["Print_Rooms_MarginLeft"]));
            }
            set {
                this["Print_Rooms_MarginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_Subject_Height {
            get {
                return ((int)(this["Print_Subject_Height"]));
            }
            set {
                this["Print_Subject_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_Subject_Width {
            get {
                return ((int)(this["Print_Subject_Width"]));
            }
            set {
                this["Print_Subject_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Print_Subject_MarginLeft {
            get {
                return ((int)(this["Print_Subject_MarginLeft"]));
            }
            set {
                this["Print_Subject_MarginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_Homework_Height {
            get {
                return ((int)(this["Print_Homework_Height"]));
            }
            set {
                this["Print_Homework_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_Homework_Width {
            get {
                return ((int)(this["Print_Homework_Width"]));
            }
            set {
                this["Print_Homework_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Print_Homework_MarginLeft {
            get {
                return ((int)(this["Print_Homework_MarginLeft"]));
            }
            set {
                this["Print_Homework_MarginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_School_Height {
            get {
                return ((int)(this["Print_School_Height"]));
            }
            set {
                this["Print_School_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int Print_School_Width {
            get {
                return ((int)(this["Print_School_Width"]));
            }
            set {
                this["Print_School_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Print_School_MarginLeft {
            get {
                return ((int)(this["Print_School_MarginLeft"]));
            }
            set {
                this["Print_School_MarginLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Print_Header_Height {
            get {
                return ((int)(this["Print_Header_Height"]));
            }
            set {
                this["Print_Header_Height"] = value;
            }
        }
    }
}
